# available when running the deployment in Pipeline CI
banzaicloud:
  tags: []
  organization:
    name:
  cluster:
    id:
    name:
    cloud:
    distribution:
    location:

pipeline-monitor:
  enabled: true

pipeline-ingress:
  enabled: false

istio:
  enabled: false

postgresql:
  enabled: true
  postgresqlDatabase:
  existingSecret:

redis:
  enabled: true
  redisDatabase:
  existingSecret:
  
deployment:
  image:
    repository: moznSystems/spotguide-flask-postgres-redis
    tag: latest
    pullPolicy: Always
  args: ["node", ".", "--max-old-space-size", "$(MEMORY_LIMIT)"]
  replicaCount: 1
  maxUnavailable: 0
  maxSurge: 1
  revisionHistoryLimit: 10
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  ## Pod Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  serviceAccountName:
  podAnnotations:
  livenessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 20
    periodSeconds: 10
  env: []
  envSecrets: []
  envConfigMaps: []
  envResourceField:
    - name: MEMORY_LIMIT
      resourceFieldRef:
        resource: limits.memory
        divisor: 1Mi
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
ingress:
  tls: []
  hosts: []
  annotations: {}
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
